version: "3.7"
services:

    locust:
        container_name: quay-tester
        image: locustio/locust
        ports:
            - "8089:8089"
        volumes:
            - ./:/mnt/
        environment:
            PYTHONPATH: '/mnt'
        command: -f /mnt/testfiles/podman_operations.py
        network_mode: host

    locust-metrics-exporter:
        image: containersol/locust_exporter
        ports:
            - "9646:9646"
        environment:
            - LOCUST_EXPORTER_URI=http://localhost:8089
        network_mode: host
        depends_on:
            - locust

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        network_mode: host
        ports:
            - "9090:9090"
        command:
            - --config.file=/prometheus.yaml
        volumes:
            - ./prometheus.yaml:/prometheus.yaml:ro
